name: Playwright tests

on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx github-actions-ctrf ctrf/ctrf-report.json

      - name: Upload CTRF report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ctrf-report
          path: |
            ctrf/ctrf-report.json
            playwright-report
